"use strict";
exports.__esModule = true;
var claseMobileP_1 = require("./claseMobileP");
var mobileLibraryP_1 = require("./mobileLibraryP");
var Nokia3210 = new claseMobileP_1.MobileP("Nokia", " 3210", " Nokia", 2, " Gris", false, 0, 15);
var iPhone3G = new claseMobileP_1.MobileP("iPhone", " 3G", " Apple", 18, " Negro o Blanco", false, 1, 80);
var Samsung_Galaxy10 = new claseMobileP_1.MobileP("Samsung", " Galaxy10", " Samsung", 64, " Negro o Blanco", true, 2, 700);
var XiaomiMi9 = new claseMobileP_1.MobileP("Xiaomi", " Mi9", " Xiaomi", 128, " Negro o Blanco", true, 3, 450);
var MotorolaRazrV3 = new claseMobileP_1.MobileP("Motorola", " Razr V3", " Motorola", 128, " Negro o Blanco", true, 2, 1450);
var OnePlus8 = new claseMobileP_1.MobileP("One Plus", " pro 8", " One Plus", 64, " Negro o Blanco", true, 5, 909);
var arrmobile1 = [Nokia3210, iPhone3G, Samsung_Galaxy10, XiaomiMi9];
var arrmobile2 = [MotorolaRazrV3, OnePlus8];
var library1 = new mobileLibraryP_1.MobileLibrary("Worten", "Madrid", arrmobile1);
var library2 = new mobileLibraryP_1.MobileLibrary("FNAC", "Ciudad Real", arrmobile2);
console.log(library2.getName());
console.log(library2.getLocation());
library2.setName("Mediamarkt");
library2.setLocation("Valladolid");
console.log(library2.getName());
console.log(library2.getLocation());
library2.printLibrary();
